name: Java CI/CD and Docker Packaging with Telegram Alerts
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-pack:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'


      - name: Build with Maven
        run: mvn -B package --file pom.xml


      - name: Build Docker Image
        run: |
          docker build -t my-web-app:${{ github.sha }} .
          docker tag my-web-app:${{ github.sha }} my-web-app:latest


      - name: Send Telegram Notification on Success
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🚀 CI/CD Pipeline Success!
            📌 Repository: ${{ github.repository }}
            🌿 Branch: ${{ github.ref_name }}
            📝 Commit: "${{ github.event.head_commit.message }}"
            ✅ The project compiled successfully and the Docker image is ready for deployment.


      - name: Send Telegram Notification on Failure
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ❌ CI/CD Pipeline Failed!
            📌 Repository: ${{ github.repository }}
            🌿 Branch: ${{ github.ref_name }}
            ⚠️ An error occurred during the compilation or Docker packaging phase. Please check the GitHub Actions logs.